packages:
  - web
  - studio

overrides:
  "string.prototype.repeat>es-abstract": 1.23.10

allowBuilds:
  "@sentry/cli": true
  esbuild: true

peerDependencyRules:
  allowedVersions:
    "@sanity/migrate>@sanity/cli-core": "1 || 2"
