export {
  APP_PERMISSIONS,
  APP_ROLES,
  canAccessAdminPanel,
  canAccessDashboard,
  createPermissionChecker,
  DASHBOARD_PERMISSION_ACTIONS,
  DASHBOARD_PERMISSION_RESOURCES,
  DASHBOARD_RESOURCE_PERMISSION_LIST,
  DASHBOARD_RESOURCE_PERMISSIONS,
  getDashboardRequestPermission,
  getDashboardResourcePermission,
  getRolePermissions,
  hasAnyPermission,
  hasDashboardResourcePermission,
  hasEveryPermission,
  hasPermission,
  isAppRole,
  PERMISSIONS,
  ROLE_PERMISSIONS,
} from "../../../shared/auth/permissions";
export type {
  AppPermission,
  AppRole,
  CorePermission,
  DashboardPermissionAction,
  DashboardPermissionResource,
  DashboardResourcePermission,
  DashboardResourcePermissionAction,
  PermissionChecker,
} from "../../../shared/auth/permissions";
