export const players = [
  {
    id: 1,
    firstName: "Juan",
    lastName: "Pérez",
    position: 4, // 1: ARQ, 2: DEF, 3: MED, 4: DEL
    number: 10,
    heigth: 180,
    weight: 75,
    goals: 15,
    assists: 5,
  },
  {
    id: 2,
    firstName: "Carlos",
    lastName: "Gómez",
    position: 3,
    number: 8,
    heigth: 175,
    weight: 70,
    goals: 5,
    assists: 10,
  },
  {
    id: 3,
    firstName: "Luis",
    lastName: "Rodríguez",
    position: 2,
    number: 5,
    heigth: 185,
    weight: 80,
    goals: 2,
    assists: 3,
  },
  {
    id: 4,
    firstName: "Miguel",
    lastName: "Sánchez",
    position: 1,
    number: 1,
    heigth: 190,
    weight: 85,
    goals: 0,
    assists: 0,
  },
  {
    id: 5,
    firstName: "Andrés",
    lastName: "Fernández",
    position: 4,
    number: 9,
    heigth: 178,
    weight: 72,
    goals: 12,
    assists: 4,
  },
];
