export const table = [
  {
    id: 1,
    position: 5,
    team: "Mentira FC",
    played: 30,
    won: 14,
    drawn: 8,
    lost: 8,
    goalsFor: 45,
    goalsAgainst: 35,
    goalDifference: 10,
    points: 50
  },
  {
    
    id: 2,
    position: 1,
    team: "Equipo A",
    played: 30,
    won: 20,
    drawn: 5,
    lost: 5,
    goalsFor: 60,
    goalsAgainst: 30,
    goalDifference: 30,
    points: 65
  },
  {
    id: 3,
    position: 2,
    team: "Equipo B",
    played: 30,
    won: 18,
    drawn: 8,
    lost: 4,
    goalsFor: 55,
    goalsAgainst: 25,
    goalDifference: 30,
    points: 62
  },
  {
    id: 4,
    position: 3,
    team: "Equipo C",
    played: 30,
    won: 17,
    drawn: 7,
    lost: 6,
    goalsFor: 50,
    goalsAgainst: 28,
    goalDifference: 22,
    points: 58
  },
  {
    id: 5,
    position: 4,
    team: "Equipo D",
    played: 30,
    won: 15,
    drawn: 10,
    lost: 5,
    goalsFor: 48,
    goalsAgainst: 30,
    goalDifference: 18,
    points: 55
  },
  {
    id: 6,
    position: 6,
    team: "Equipo E",
    played: 30,
    won: 13,
    drawn: 9,
    lost: 8,
    goalsFor: 40,
    goalsAgainst: 32,
    goalDifference: 8,
    points: 48
  },
  {
    id: 7,
    position: 7,
    team: "Equipo F",
    played: 30,
    won: 12,
    drawn: 10,
    lost: 8,
    goalsFor: 38,
    goalsAgainst: 34,
    goalDifference: 4,
    points: 46
  },
  {
    id: 8,
    position: 8,
    team: "Equipo G",
    played: 30,
    won: 11,
    drawn: 11,
    lost: 8,
    goalsFor: 36,
    goalsAgainst: 36,
    goalDifference: 0,
    points: 44
  },
  {
    id: 9,
    position: 9,
    team: "Equipo H",
    played: 30,
    won: 10,
    drawn: 12,
    lost: 8,
    goalsFor: 34,
    goalsAgainst: 38,
    goalDifference: -4,
    points: 42
  },
  {
    id: 10,
    position: 10,
    team: "Equipo I",
    played: 30,
    won: 9,
    drawn: 13,
    lost: 8,
    goalsFor: 32,
    goalsAgainst: 40,
    goalDifference: -8,
    points: 40
  }
]