export const ROUTES = {
  HOME: "/",
  NEWS: "/noticias",
  GALLERY: "/galeria",
  TEAM: "/plantel",
  TABLE: "/tabla",
  RECORD: "/historial",
  LOGIN: "/ingresar",
  PASSWORD_RESET_REQUEST: "/recuperar-contrasena",
  PASSWORD_RESET_UPDATE: "/nueva-contrasena",
  ACCOUNT: "/mi-cuenta",
  ADMIN: "/admin",
  ADMIN_COMMENT_REPORTS: "/admin/reportes-comentarios",
  ADMIN_USERS: "/admin/usuarios",
  ADMIN_ROLES: "/admin/roles-permisos",
  ADMIN_FOOTER_SETTINGS: "/admin/footer-sponsors",
  ADMIN_AUDIT_LOG: "/admin/audit-log",
  ADMIN_METRICS: "/admin/metricas",
  ADMIN_AUTH_CONTROLS: "/admin/auth",
  ADMIN_FEATURE_FLAGS: "/admin/feature-flags",
  ADMIN_MAINTENANCE: "/admin/mantenimiento",
  DASHBOARD: "/dashboard",
  DASHBOARD_NEWS: "/dashboard/noticias",
  DASHBOARD_NEWS_NEW: "/dashboard/noticias/nueva",
  DASHBOARD_MATCHES: "/dashboard/partidos",
  DASHBOARD_MATCHES_NEW: "/dashboard/partidos/nuevo",
  DASHBOARD_GALLERIES: "/dashboard/galerias",
  DASHBOARD_GALLERIES_NEW: "/dashboard/galerias/nueva",
  DASHBOARD_TABLE: "/dashboard/tabla",
  DASHBOARD_TABLE_NEW: "/dashboard/tabla/nueva",
  DASHBOARD_TOURNAMENTS: "/dashboard/torneos",
  DASHBOARD_TOURNAMENTS_NEW: "/dashboard/torneos/nuevo",
  DASHBOARD_ORGANIZATIONS: "/dashboard/organizadores",
  DASHBOARD_ORGANIZATIONS_NEW: "/dashboard/organizadores/nuevo",
  DASHBOARD_TEAMS: "/dashboard/clubes",
  DASHBOARD_TEAMS_NEW: "/dashboard/clubes/nuevo",
  DASHBOARD_PLAYERS: "/dashboard/jugadores",
  DASHBOARD_PLAYERS_NEW: "/dashboard/jugadores/nuevo",
  DASHBOARD_STAFF_NEW: "/dashboard/jugadores/staff/nuevo",
  DASHBOARD_COMMENTS_MODERATION: "/dashboard/moderacion-comentarios",

  NEWS_DETAIL: (slug: string) => `/noticias/${slug}`,
  GALLERY_DETAIL: (slug: string) => `/galeria/${slug}`,
  PLAYER_DETAIL: (slug: string) => `/plantel/${slug}`,
  STAFF_DETAIL: (slug: string) => `/plantel/staff/${slug}`,
  DASHBOARD_NEWS_EDIT: (id: string) => `/dashboard/noticias/${id}`,
  DASHBOARD_MATCHES_EDIT: (id: string) => `/dashboard/partidos/${id}`,
  DASHBOARD_GALLERIES_EDIT: (id: string) => `/dashboard/galerias/${id}`,
  DASHBOARD_TABLE_EDIT: (id: string) => `/dashboard/tabla/${id}`,
  DASHBOARD_TOURNAMENTS_EDIT: (id: string) => `/dashboard/torneos/${id}`,
  DASHBOARD_ORGANIZATIONS_EDIT: (id: string) =>
    `/dashboard/organizadores/${id}`,
  DASHBOARD_TEAMS_EDIT: (id: string) => `/dashboard/clubes/${id}`,
  DASHBOARD_PLAYERS_EDIT: (id: string) => `/dashboard/jugadores/${id}`,
  DASHBOARD_STAFF_EDIT: (id: string) => `/dashboard/jugadores/staff/${id}`,
};
